export const CATALOG =[
  {
  label: '🛠 Generic Tools',
  collapsed: false,
  generic: true,
  elements:[
  { id: 'hide-element',   label: 'Hide Any Element',         desc: 'Hide any element by class or ID', type: 'hide' },
  { id: 'bg-replace',     label: 'Replace Background Image', desc: "Replace a container's background with a custom image URL", type: 'background' },
  { id: 'img-replace',    label: 'Replace Image Element',    desc: 'Replace the src of an <img> using CSS content trick', type: 'img-replace' },
  { id: 'color-override', label: 'Color Override',           desc: 'Change text, background, or border color on any element', type: 'color' },
  { id: 'font-override',  label: 'Font Override',            desc: 'Replace the font globally or on a specific element', type: 'font' },
  { id: 'custom-rule',    label: 'Custom CSS Rule',          desc: 'Write any CSS property manually for any selector', type: 'custom' },
  ],
  },

  {
  label: 'Home Screen — Background & Layout',
  collapsed: true,
  elements:[
  { cls: '.parties-background',         label: 'Decorative background layer',          props:[{ type: 'bg-replace', hideImg: '.parties-background img' }, 'background-color', 'opacity'] },
  { cls: ':host .lol-uikit-background-switcher-image', label: 'Background switcher image (host context)', props: [{ type: 'img-replace', label: 'Replace background switcher image' }, 'filter', 'opacity'] },
  { cls: '.parties-view .parties-background lol-uikit-background-switcher', label: 'Party lobby background switcher', props:[{ type: 'img-replace', label: 'Replace party background' }, 'filter', 'width'] },
  { cls: '.bg-current',                 label: 'Active background image container',    props:[{ type: 'bg-replace', hideImg: '.bg-current img' }, 'background-size', 'background-position', 'opacity'] },
  { cls: '.parties-view',               label: 'Home screen root container',           props: ['background-color', 'opacity'] },
  { cls: '.parties-background-mask',    label: 'Mask overlay on background',           props:['opacity', 'display', 'background-color'] },
  { cls: '.parties-content',            label: 'Main content area',                    props: ['background-color', 'opacity'] },
  { cls: '.parties-lower-section',      label: 'Bottom section of home screen',        props:['background-color', 'opacity', 'display'] },
  { cls: '.navbar_backdrop',            label: 'Full navbar backdrop',                 props: ['background-color', 'opacity', 'display'] },
  { cls: '.navbar-blur',                label: 'Blurred backdrop behind navbar',       props: ['backdrop-filter', 'opacity', 'display'] },
  { cls: '.lol-uikit-background-switcher-image', label: 'Background img tag — hide this to replace bg', props: ['opacity', 'display'] },
  { cls: '.parties-notifications',      label: 'Party notifications area',             props: ['display', 'opacity'] },
  { cls: '.background-vignette-container', label: 'Dark vignette overlay on edges',    props:['opacity', 'display'] },
  { cls: '.background-edge-backlight',  label: 'Glowing edge backlight effect',        props: ['opacity', 'display'] },
  { cls: '.parties-lower-section-fade-in', label: 'Bottom section fade animation',     props: ['animation', 'animation-duration'] },
  { cls: '.lobby-intro-animation-container', label: 'Lobby intro fly-in animation',    props: ['animation', 'display'] },
  ],
  },

  {
  label: 'Play Button',
  collapsed: true,
  elements:[
  { cls: '.play-button-container',             label: 'Play button container',                       props:['background-color', 'background', 'border-color', 'border-radius', 'filter', 'opacity', 'transition'] },
  { cls: '.play-button-frame',                 label: 'Decorative frame behind button',              props:['display', 'background-image', 'opacity'] },
  { cls: '.play-button-text',                  label: 'Play button label text',                      props: ['color', 'font-family', 'opacity'] },
  { cls: '.play-button-video',                 label: 'Button background video',                     props: ['display', 'opacity'] },
  { cls: '.play-button-content',               label: 'Play button inner content',                   props:['opacity', 'scale', 'display'] },
  { cls: '.play-button-hover-magic',           label: 'Hover magic effect',                          props: ['display', 'opacity'] },
  ],
  },

  {
  label: 'Navigation — Top Bar & Controls',
  collapsed: true,
  elements:[
  { cls: '.riotclient-app-controls',     label: 'Window controls container (top right)', props: ['display', 'opacity'] },
  { cls: '.app-controls-support',        label: 'Support button',                      props: ['display'] },
  { cls: '.app-controls-hide',           label: 'Minimize button',                     props: ['display'] },
  { cls: '.app-controls-settings',       label: 'Settings cog button',                 props: ['display'] },
  { cls: '.app-controls-close',          label: 'Close button',                        props: ['display'] },
  { cls: '.navigation-status-ticker',    label: 'Status ticker bar (incidents/maintenance)', props:['display', 'opacity'] },
  { cls: '.navigation-status-ticker-content', label: 'Status ticker content',          props: ['display', 'opacity'] },
  { cls: '.ticker-button',               label: 'Status ticker toggle button',          props: ['display'] },
  { cls: '.play-button-frame',           label: 'Play button decorative frame',         props: ['display', 'opacity'] },
  { cls: '.play-button-hover-magic',     label: 'Play button hover magic effect',       props:['display', 'opacity'] },
  { cls: '.play-button-text',            label: 'Play button label text',               props: ['color', 'font-family', 'opacity'] },
  { cls: '.play-button-video',           label: 'Play button background video',         props: ['display', 'opacity'] },
  { cls: '.league-logo',                 label: 'League of Legends logo',               props:['display', 'opacity', 'filter'] },
  { cls: '.call-to-action-pip',          label: 'CTA notification pip/dot',             props: ['display', 'opacity'] },
  { cls: '.pip-cta-loop',                label: 'CTA pip loop animation',               props:['animation', 'display', 'opacity'] },
  { cls: '.bug-report-button',           label: 'Bug report button',                    props: ['display', 'opacity'] },
  ],
  },

  {
  label: 'Navigation — Active State & Section Glow',
  collapsed: true,
  elements:[
  { cls: 'lol-uikit-navigation-bar',           label: 'Navigation bar root element',                props:['filter', 'background-color', 'opacity'] },
  { cls: '.navigation-bar.left',               label: 'Left navigation bar',                        props: ['filter', 'background-color', 'display'] },
  { cls: '.section',                           label: 'Nav section item (all states)',                props:['color', 'font-family', 'text-shadow', 'background-image'] },
  { cls: '.section.active',                    label: 'Active nav section',                          props:['color', 'font-family', 'text-shadow', 'background-image'] },
  { cls: 'lol-uikit-full-page-backdrop',       label: 'Full page modal backdrop',                   props: ['background-color', 'background', 'opacity'] },
  { cls: 'lol-regalia-banner-v2-element',      label: 'Regalia rank banner element',                props: ['filter', 'opacity', 'display'] },
  { cls: '.section-glow',                      label: 'Gold glow line under active nav item',        props:['background', 'display', 'opacity', 'height'] },
  ],
  },

  {
  label: 'Navigation — Left Side',
  collapsed: true,
  elements:[
  { cls: '.left-nav-menu',              label: 'Left navigation container',            props: ['background-color', 'opacity', 'display'] },
  { cls: '.deep-links-promo',           label: 'Riot promo banner',                    props:['display', 'opacity'] },
  { cls: '.deep-links-promo-element',   label: 'Individual promo element',             props: ['display', 'opacity'] },
  { cls: '.launch-lor-button',          label: 'Legends of Runeterra button',          props: ['display', 'opacity'] },
  { cls: '.launch-lor-button-arrow',    label: 'LoR button arrow decoration',          props: ['display', 'opacity'] },
  { cls: '.launch-lor-button-container',label: 'LoR button container',                 props: ['display', 'opacity'] },
  ],
  },

  {
  label: 'Navigation — Right Side & Mode Icons',
  collapsed: true,
  elements:[
  { cls: '.right-nav-menu',              label: 'Right navigation container',          props: ['background-color', 'opacity', 'display'] },
  { cls: '.right-nav-vertical-rule',     label: 'Vertical dividers between nav icons', props:['display', 'opacity', 'background-color'] },
  { cls: '.menu-item-icon-wrapper',      label: 'Nav icon wrapper',                    props: ['background-color', 'opacity'] },
  { cls: '.menu-item-icon',              label: 'Nav icon image',                      props: ['opacity', 'filter'] },
  { cls: '.menu-item-glow',              label: 'Glow effect on nav icons',            props:['display', 'opacity'] },
  { cls: '.menu_item_navbar_tft',        label: 'TFT tab',                             props: ['display'] },
  { cls: '.menu_item_navbar_store',      label: 'Store tab',                           props: ['display'] },
  { cls: '.menu_item_navbar_loot',       label: 'Loot tab',                            props: ['display'] },
  { cls: '.menu_item_navbar_competitive',label: 'Ranked tab',                          props: ['display'] },
  { cls: '.menu_item_navbar_collection', label: 'Collection tab',                      props: ['display'] },
  { cls: '.menu_item_navbar_yourshop',   label: 'Your Shop tab',                       props: ['display'] },
  { cls: '.menu_item_navbar_league',     label: 'League tab',                          props: ['display'] },
  ],
  },

  {
  label: 'Player Identity & Profile Display',
  collapsed: true,
  elements:[
  { cls: '.player-identity-container',       label: 'Player identity block container',    props: ['display', 'opacity'] },
  { cls: '.player-identity-animation-container', label: 'Player identity animation',      props: ['animation', 'opacity', 'display'] },
  { cls: '.player-identity-gem-animation',   label: 'Gem animation on identity',          props: ['animation', 'display', 'opacity'] },
  { cls: '.player-name-container',           label: 'Player name container',               props:['display', 'opacity'] },
  { cls: '.player-name',                     label: 'Player display name text',            props: ['color', 'font-family', 'font-size', 'opacity', 'display'] },
  { cls: '.player-name__game-name',          label: 'Game name portion of player name',    props: ['color', 'font-family'] },
  { cls: '.summoner-level-icon',             label: 'Level badge icon',                    props: ['display', 'opacity'] },
  { cls: '.summoner-level-ring',             label: 'XP ring around level badge',          props:['display', 'opacity', 'filter'] },
  { cls: '.summoner-level',                  label: 'Level number text',                   props: ['color', 'display', 'opacity'] },
  { cls: '.xp-ring',                         label: 'XP progress ring',                    props: ['display', 'opacity', 'left', 'top', 'width', 'height'] },
  // Avatar image — hide img, replace via background on container
  { cls: '.lol-social-avatar',               label: 'Player avatar/icon container',        props:[{ type: 'bg-replace', hideImg: '.lol-social-avatar img', label: 'Replace avatar image' }, 'opacity', 'filter', 'border-radius', 'width', 'height'] },
  { cls: '.icon-image',                      label: 'Avatar icon — replace image',               props:[{ type: 'img-replace', label: 'Replace icon image' }, 'opacity', 'display', 'filter'] },
  { cls: '.icon-ring',                       label: 'Ring around avatar icon',             props: ['display', 'opacity', 'filter'] },
  { cls: '.portrait-icon',                   label: 'Portrait icon (champ select / assignment)', props:['opacity', 'filter', 'display'] },
  ],
  },

  {
  label: 'Social Panel & Chat',
  collapsed: true,
  elements:[
  { cls: '.availability-icon.open-party',      label: 'Status dot — Open Party',                     props: ['background-color', 'background-image'] },
  { cls: '.lol-social-sidebar',                label: 'Social sidebar container',                    props:['background-color', 'opacity', 'display'] },
  { cls: '.status-message-wrapper',            label: 'Status message text wrapper',                 props: ['color', 'font-family', 'opacity'] },
  { cls: '.availability-icon',                 label: 'Online status dot (default)',                  props:['background-color', 'border-color', 'filter'] },
  { cls: 'lol-social-chat-input .chat-input',  label: 'Chat input field',                            props:['filter', 'background-color', 'border-color'] },
  { cls: '.lol-social-identity',               label: 'Player identity in social bar',               props: ['background-color', 'opacity'] },
  { cls: '.lol-social-roster',                 label: 'Friends roster list',                         props: ['background-color', 'opacity'] },
  { cls: '.status-message.offline',            label: 'Status message — offline state',              props: ['color', 'opacity'] },
  { cls: 'lol-social-panel',                   label: 'Full social panel',                           props: ['filter', 'opacity', 'display'] },
  { cls: '.lol-social-identity .notifications-button', label: 'Notifications button in social',      props:['filter', 'opacity', 'display'] },
  { cls: '.availability-icon.chat',            label: 'Status dot — Online (green)',                 props: ['background-color', 'border-color'] },
  { cls: '.availability-icon.away',            label: 'Status dot — Away (yellow)',                  props:['background-color', 'border-color'] },
  { cls: '.social-count-badge',                label: 'Notification count badge',                    props: ['background-color', 'color', 'border-radius'] },
  { cls: '.mission-button .count-badge',       label: 'Mission button count badge',                  props:['background-color', 'color'] },
  { cls: '.chat-bubble .my-bubble',            label: 'My chat bubble color',                        props: ['background-color', 'border-color'] },
  { cls: 'lol-social-chat-window .conversation.active::before', label: 'Active conversation indicator', props: ['background-color'] },
  { cls: 'lol-social-roster-member .open-party .open-party-indicator', label: 'Open party indicator (friend)', props:['background-color'] },
  { cls: '.chat-header',                       label: 'Chat window header',                          props:['border-color', 'background-color', 'color'] },
  { cls: '.status-message.chat',               label: 'Status message — online state',               props: ['color', 'font-family'] },
  { cls: '.status-message.away',               label: 'Status message — away state',                 props: ['color'] },
  { cls: '.status-message.open-party.chat',    label: 'Status message — open party',                props: ['color'] },
  { cls: 'lol-social-chat-window .conversation.unread .conversation-subtitle', label: 'Unread conversation text', props: ['color'] },
  { cls: 'lol-social-friend-requests .friend-requests-header', label: 'Friend requests header text', props: ['color'] },
  { cls: 'lol-social-status .status-message.dnd', label: 'DND status text (Do Not Disturb)',        props:['color', 'font-family'] },
  { cls: '.availability-icon.mobile',          label: 'Status dot — Mobile',                         props: ['background-color', 'display'] },
  { cls: '.lol-social-actions-bar',            label: 'Social action buttons bar',                   props: ['display', 'opacity'] },
  { cls: '.arrow-container',                   label: 'Friend list expand/collapse arrows',          props: ['display', 'opacity'] },
  { cls: '.filled.xp-ring',                   label: 'Filled XP ring color',                        props: ['background-color', 'opacity', 'left', 'top', 'width', 'height'] },
  { cls: '.xp-ring:not(.filled)',              label: 'Empty XP ring track',                         props: ['background-color', 'opacity', 'left', 'top', 'width', 'height'] },
  ],
  },

  {
  label: 'Currency & Wallet',
  collapsed: true,
  elements:[
  { cls: '.wallet-and-badges',            label: 'RP and BE wallet container',          props: ['display', 'opacity'] },
  { cls: '.currency-rp-container-top-up-enabled', label: 'RP currency container',       props:['display', 'opacity'] },
  { cls: '.currency-rp-top-up',           label: 'RP amount display',                   props: ['display', 'opacity', 'color'] },
  { cls: '.currency-be',                  label: 'Blue Essence container',              props: ['display', 'opacity'] },
  { cls: '.currency-be-text',             label: 'Blue Essence amount text',            props:['color', 'display', 'opacity'] },
  { cls: '.currency-be-icon-container-top-up-enabled', label: 'BE icon container',      props: ['display', 'opacity'] },
  { cls: '.animation-add-blue-essence',   label: 'BE gain animation',                   props: ['animation', 'display'] },
  { cls: '.animation-remove-blue-essence',label: 'BE spend animation',                  props: ['animation', 'display'] },
  { cls: '.persistent-header-opal__currency-container', label: 'Currency in activity center header', props: ['display', 'opacity'] },
  ],
  },

  {
  label: 'Ready Check & Match Accept',
  collapsed: true,
  elements:[
  { cls: '.ready-check-root-element',                    label: 'Ready check overlay root',                props: ['opacity', 'filter', 'background-color', 'animation'] },
  { cls: '.ready-check-accept',                          label: 'Accept button',                           props:['background-color', 'border-color', 'color', 'filter'] },
  { cls: '.ready-check-decline',                         label: 'Decline button',                          props:['background-color', 'border-color', 'color', 'filter'] },
  { cls: '.ready-check-timer.ember-view',                label: 'Timer ember view',                        props: ['opacity', 'animation'] },
  { cls: '.fake-application-template',                   label: 'Match accept overlay template',           props: ['animation', 'opacity'] },
  { cls: '.ready-check-state-machine-timer',             label: 'Accept timer animation',                  props:['filter', 'opacity', 'animation', 'animation-duration'] },
  { cls: '.ready-check-timer',                           label: 'Countdown timer ring',                    props: ['opacity', 'filter'] },
  ],
  },

  {
  label: 'Champion Select — Background & Layout',
  collapsed: true,
  elements:[
  { cls: '.champ-select-bg',               label: 'Champion select main background',         props:[{ type: 'bg-replace', hideImg: '.champ-select-bg img' }, 'background-color', 'opacity'] },
  { cls: '.champ-select-bg-darken',        label: 'Darkening overlay on background',         props: ['opacity', 'background-color', 'display'] },
  { cls: '.champion-splash-background',    label: 'Champion splash art behind the UI',       props:[{ type: 'bg-replace', hideImg: '.champion-splash-background img' }, 'opacity', 'filter', 'display'] },
  { cls: '.champion-background-image',     label: 'Individual champion background',          props:[{ type: 'bg-replace', hideImg: '.champion-background-image img' }, 'opacity', 'filter', 'display'] },
  { cls: '.champion-splash-ring',          label: 'Decorative ring around splash art',       props: ['display', 'opacity'] },
  { cls: '.top-darken',                    label: 'Top edge darkening gradient',              props:['opacity', 'display'] },
  { cls: '.image-magic-background',        label: 'Magic/animated background effect',        props: ['opacity', 'display', 'animation'] },
  { cls: '.lane-intro-video',              label: 'Lane intro video overlay',                props: ['display', 'opacity'] },
  { cls: '.map-intro-video',               label: 'Map intro video',                         props:['display', 'opacity'] },
  { cls: '.map-static-image',              label: 'Static map image fallback',               props:[{ type: 'img-replace', label: 'Replace map image' }, 'opacity', 'filter'] },
  { cls: '.slash-video',                   label: 'Slash screen video',                      props:['display', 'opacity'] },
  { cls: '.blue-ban-video',                label: 'Blue team ban video',                     props: ['display', 'opacity'] },
  { cls: '.red-ban-video',                 label: 'Red team ban video',                      props: ['display', 'opacity'] },
  { cls: '.phase-transition-visibility-wrapper', label: 'Phase transition full-screen overlay', props:['display', 'opacity'] },
  { cls: '.phase-transition-text',         label: 'Phase text (e.g. "Banning Phase")',       props: ['color', 'font-family', 'display'] },
  { cls: '.phase-transition-text-glow',    label: 'Glow behind phase text',                  props: ['display', 'opacity'] },
  { cls: '.phase-transition-label',        label: 'Phase transition label',                  props: ['color', 'display'] },
  ],
  },

  {
  label: 'Champion Select — Summoner Slots',
  collapsed: true,
  elements:[
  { cls: '.summoner-array',             label: 'Row of all summoner slots',                  props: ['opacity', 'display'] },
  { cls: '.summoner-wrapper',           label: 'Individual summoner slot wrapper',            props: ['background-color', 'opacity'] },
  { cls: '.summoner-object',            label: 'Summoner slot element',                      props:['background-color', 'opacity'] },
  { cls: '.summoner-name',              label: 'Summoner name in slot',                       props: ['color', 'font-family', 'font-size'] },
  { cls: '.summoner-primary-text',      label: 'Primary text (champion name) in slot',       props:['color', 'font-family'] },
  { cls: '.summoner-primary-text-glow', label: 'Glow behind primary text',                   props: ['display', 'opacity'] },
  { cls: '.summoner-secondary-text',    label: 'Secondary text in slot',                     props:['color', 'font-family', 'display'] },
  { cls: '.summoner-timer',             label: 'Per-summoner action timer',                  props: ['display', 'opacity', 'color'] },
  { cls: '.summoner-muted-icon',        label: 'Mute indicator on summoner',                 props:['display', 'opacity'] },
  { cls: '.summoner-spells',            label: 'Summoner spells display',                    props: ['display', 'opacity'] },
  { cls: '.my-team',                    label: 'Your team side container',                   props: ['background-color', 'opacity'] },
  { cls: '.their-team',                 label: 'Enemy team side container',                  props: ['background-color', 'opacity'] },
  { cls: '.enemy-party',                label: 'Enemy party container',                      props:['background-color', 'opacity'] },
  { cls: '.is-acting-now',              label: 'Slot highlight — currently picking/banning', props: ['outline-color', 'background-color'] },
  { cls: '.local-player-acting',        label: 'Your slot highlight — your turn',            props:['outline-color', 'background-color'] },
  { cls: '.champion-container',         label: 'Champion display container in slot',         props: ['background-color', 'opacity'] },
  { cls: '.champion-icon-container',    label: 'Champion icon in slot',                      props: ['opacity', 'filter'] },
  ],
  },

  {
  label: 'Champion Select — Champion Grid & Search',
  collapsed: true,
  elements:[
  { cls: '.champion-grid',             label: 'Champion picker grid',                         props: ['background-color', 'opacity'] },
  { cls: '.champion-grid-header',      label: 'Grid header with search/sort',                 props:['background-color', 'opacity', 'display'] },
  { cls: '.champion-grid-champion-thumbnail', label: 'Individual champion thumbnail',         props:[{ type: 'img-replace', label: 'Replace champion thumbnail' }, 'opacity', 'filter'] },
  { cls: '.champion-grid-toggle',      label: 'Toggle to show/hide grid',                     props: ['display', 'opacity'] },
  { cls: '.champion-input',            label: 'Champion search input field',                  props:['background-color', 'color', 'border-color'] },
  { cls: '.champion-name',             label: 'Champion name label',                          props:['color', 'font-family'] },
  { cls: '.champion-icons',            label: 'Champion icons container',                     props: ['opacity'] },
  { cls: '.champion-icons-bg',         label: 'Background behind champion icons',             props: ['background-color', 'opacity', 'display'] },
  { cls: '.champ-select-sort-dropdown',label: 'Sort dropdown in grid',                        props:['display', 'opacity'] },
  { cls: '.champion-preview-hover-timer', label: 'Preview timer on hover',                    props: ['display', 'opacity'] },
  { cls: '.champion-preview-champion-difficulty-plate', label: 'Champion difficulty plate',   props: ['display', 'opacity'] },
  { cls: '.vote-reveal',               label: 'Vote reveal animation area',                   props:['display', 'opacity', 'animation'] },
  { cls: '.vote-reveal-champion-name', label: 'Champion name in vote reveal',                 props: ['color', 'display'] },
  { cls: '.vote-reveal-label',         label: 'Vote reveal label',                            props: ['color', 'display'] },
  { cls: '.grid-champion-free-to-play',label: 'Free to play champion overlay',                props: ['display', 'opacity'] },
  { cls: '.grid-champion-overlay',     label: 'Champion grid overlay (locked/unavailable)',   props: ['display', 'opacity'] },
  ],
  },

  {
  label: 'Champion Select — Skins',
  collapsed: true,
  elements:[
  { cls: '.skin-selection-carousel',   label: 'Skin picker carousel',                         props:['display', 'opacity'] },
  { cls: '.skin-selection-carousel-container', label: 'Carousel container',                   props: ['display', 'opacity', 'background-color'] },
  { cls: '.skin-selection-button',     label: 'Individual skin select button',                 props: ['opacity'] },
  { cls: '.skin-selection-item',       label: 'Skin item in carousel',                        props:['opacity', 'filter'] },
  { cls: '.skin-selection-thumbnail',  label: 'Skin thumbnail image',                         props:[{ type: 'img-replace', label: 'Replace skin thumbnail' }, 'opacity', 'filter'] },
  { cls: '.skin-selection-indicator',  label: 'Current skin indicator dots',                  props: ['display', 'opacity'] },
  { cls: '.skin-showcase',             label: 'Large skin preview area',                      props: ['display', 'opacity'] },
  { cls: '.skin-name-text',            label: 'Skin name label text',                         props:['color', 'font-family', 'display'] },
  { cls: '.champion-skin-name',        label: 'Champion skin name display',                   props: ['color', 'display'] },
  { cls: '.champion-ring-magic-animation-inner', label: 'Inner ring magic animation',         props: ['animation', 'display', 'opacity'] },
  { cls: '.champion-ring-magic-animation-outer', label: 'Outer ring magic animation',         props: ['animation', 'display', 'opacity'] },
  { cls: '.champion-ring-shine-animation', label: 'Ring shine effect',                        props: ['animation', 'display', 'opacity'] },
  { cls: '.champion-ring-pop-animation', label: 'Ring pop effect on selection',               props: ['animation', 'display', 'opacity'] },
  { cls: '.skin-purchase',             label: 'Skin purchase button/area',                    props: ['display', 'opacity'] },
  { cls: '.unlock-skin-hit-area',      label: 'Unlock skin click area',                       props: ['display', 'opacity'] },
  ],
  },

  {
  label: 'Champion Select — Runes & Loadout',
  collapsed: true,
  elements:[
  { cls: '.loadouts-edit-wrapper',      label: 'Rune/loadout editor wrapper',                 props:['display', 'opacity', 'background-color'] },
  { cls: '.loadout-edit-controls',      label: 'Loadout edit control buttons',                props: ['display', 'opacity'] },
  { cls: '.perks-dropdowns',            label: 'Rune page dropdowns container',               props: ['display', 'opacity'] },
  { cls: '.perks-page-dropdown',        label: 'Individual rune page dropdown',               props:['background-color', 'border-color', 'opacity'] },
  { cls: '.perks-page-name',            label: 'Rune page name text',                         props: ['color', 'font-family'] },
  { cls: '.emotes-edit-button',         label: 'Emote picker button',                         props: ['display', 'opacity'] },
  { cls: '.emotes-visibility-wrapper',  label: 'Emotes panel wrapper',                        props: ['display', 'opacity'] },
  { cls: '.ward-skin-select-component', label: 'Ward skin selector',                          props: ['display', 'opacity'] },
  { cls: '.champ-select-voice-button-wrapper', label: 'Voice chat button in champ select',    props: ['display', 'opacity'] },
  { cls: '.rune-recommender-button-component', label: 'Rune recommender button',              props: ['display', 'opacity'] },
  { cls: '.spell',                      label: 'Summoner spell icon',                         props: ['opacity', 'filter'] },
  ],
  },

  {
  label: 'Champion Select — Bans',
  collapsed: true,
  elements:[
  { cls: '.bans-container',              label: 'Ban icons row container',                    props: ['display', 'opacity', 'background-color'] },
  { cls: '.bans-list',                   label: 'List of ban icons',                          props: ['display', 'opacity'] },
  { cls: '.bans-label',                  label: 'Bans section label text',                    props:['color', 'display'] },
  { cls: '.bans-label-glow',             label: 'Glow on bans label',                         props: ['display', 'opacity'] },
  { cls: '.ban-showcase',                label: 'Ban showcase animation area',                props: ['display', 'opacity'] },
  { cls: '.ban-announcement-label',      label: '"X has been banned" label',                 props:['color', 'display', 'opacity'] },
  { cls: '.ban-announcement-text',       label: 'Ban announcement details text',              props: ['color', 'display'] },
  { cls: '.ban-announcement-bg-glow',    label: 'Glow behind ban announcement',               props:['display', 'opacity'] },
  { cls: '.ban-background-overlay-container', label: 'Darkening overlay during ban',          props: ['display', 'opacity'] },
  { cls: '.ban-bar-container',           label: 'Ban bar at top of screen',                   props: ['display', 'opacity', 'background-color'] },
  { cls: '.champ-ban-icon',              label: 'Individual banned champion icon',            props: ['opacity', 'filter'] },
  { cls: '.team-bans',                   label: 'Team bans display area',                     props: ['display', 'opacity'] },
  { cls: '.waiting-for-their-bans-label',label: 'Waiting for enemy bans label',               props:['color', 'display', 'opacity'] },
  { cls: '.waiting-for-their-bans-text', label: 'Waiting label text',                         props: ['color', 'display'] },
  { cls: '.waiting-for-their-bans-glow', label: 'Glow during ban wait state',                 props: ['display', 'opacity'] },
  { cls: '.enemy-bans-wrapper',          label: 'Enemy bans wrapper',                         props:['display', 'opacity'] },
  ],
  },

  {
  label: 'Champion Select — Timers',
  collapsed: true,
  elements:[
  { cls: '.burnout-timer',       label: 'Dodge/action burnout timer',        props: ['display', 'opacity'] },
  { cls: '.burnout-timer-bar',   label: 'Timer bar fill',                    props:['background-color', 'opacity'] },
  { cls: '.burnout-timer-glow',  label: 'Glow on timer bar',                 props: ['display', 'opacity'] },
  { cls: '.timer-status',        label: 'General timer status display',      props: ['display', 'opacity', 'color'] },
  { cls: '.timer-container',     label: 'Timer container',                   props:['display', 'opacity'] },
  ],
  },

  {
  label: 'Champion Select — Decorative Rings & Effects',
  collapsed: true,
  elements:[
  { cls: '.main-ring-container',        label: 'Main decorative ring container',              props: ['display', 'opacity'] },
  { cls: '.main-gear-container',        label: 'Gear ring container',                         props:['display', 'opacity', 'animation'] },
  { cls: '.ring-gear-component',        label: 'Gear ring component',                         props: ['display', 'opacity'] },
  { cls: '.ring-splash-dashed',         label: 'Dashed ring on splash art',                   props: ['display', 'opacity'] },
  { cls: '.ring-splash-inner',          label: 'Inner splash ring',                           props: ['display', 'opacity'] },
  { cls: '.ring-splash-outer',          label: 'Outer splash ring',                           props:['display', 'opacity'] },
  { cls: '.animated-border-overlay',    label: 'Animated border on elements',                 props: ['display', 'opacity', 'animation'] },
  { cls: '.animated-gradient-overlay',  label: 'Animated gradient overlay',                   props: ['display', 'opacity', 'animation'] },
  { cls: '.pick-ban-ring',              label: 'Ring shown during pick/ban',                  props: ['display', 'opacity'] },
  { cls: '.champion-icon-pick-snipe-glow-animation',  label: 'Pick snipe glow effect',        props:['display', 'opacity', 'animation'] },
  { cls: '.champion-icon-pick-snipe-magic-animation', label: 'Pick snipe magic effect',       props: ['display', 'opacity', 'animation'] },
  { cls: '.champion-icon-pick-snipe-ring-animation',  label: 'Pick snipe ring effect',        props: ['display', 'opacity', 'animation'] },
  { cls: '.image-ring-spinner',         label: 'Ring spinner on images',                      props: ['display', 'opacity', 'animation'] },
  ],
  },

  {
  label: 'Post-Game — Header & Result',
  collapsed: true,
  elements:[
  { cls: '.postgame-background-image',  label: 'Post-game background image',                  props:[{ type: 'bg-replace', hideImg: '.postgame-background-image img' }, 'opacity', 'filter', 'display'] },
  { cls: '.postgame-header',            label: 'Post-game header bar',                        props:['display', 'opacity', 'background-color'] },
  { cls: '.postgame-header-background', label: 'Header background',                           props: ['background-color', 'opacity'] },
  { cls: '.postgame-outcome',           label: 'Victory/Defeat display area',                 props: ['display', 'opacity'] },
  { cls: '.postgame-victory',           label: 'Victory/Defeat text',                         props:['color', 'font-family', 'font-size', 'display'] },
  { cls: '.postgame-game-result-icon',  label: 'Result icon (V/D)',                           props:['display', 'opacity', 'filter'] },
  { cls: '.postgame-game-info',         label: 'Game info container',                         props: ['display', 'opacity'] },
  { cls: '.postgame-map-icon',          label: 'Map icon in post-game',                       props: ['display', 'opacity'] },
  { cls: '.postgame-map-info-item-game-length', label: 'Game duration text',                  props: ['color', 'display'] },
  { cls: '.postgame-map-info-item-game-mode', label: 'Game mode text',                        props: ['color', 'display'] },
  { cls: '.postgame-map-info-item-win-loss', label: 'Win/loss text',                          props: ['color', 'display'] },
  { cls: '.career-postgame-countdown-meter', label: 'Auto-exit countdown meter',              props: ['display', 'opacity'] },
  { cls: '.career-postgame-countdown-meter-background', label: 'Countdown meter background',  props: ['opacity', 'background-color'] },
  ],
  },

  {
  label: 'Post-Game — Scoreboard',
  collapsed: true,
  elements:[
  { cls: '.scoreboard-root-component',       label: 'Entire scoreboard',                     props: ['background-color', 'opacity'] },
  { cls: '.scoreboard-team',                 label: 'Per-team scoreboard section',           props: ['background-color', 'opacity'] },
  { cls: '.scoreboard-header-component',     label: 'Column headers row',                    props: ['background-color', 'opacity', 'display'] },
  { cls: '.scoreboard-header-stat-label',    label: 'Column header label text',              props:['color', 'font-family', 'display'] },
  { cls: '.scoreboard-header-team-name',     label: 'Team name in header',                   props: ['color', 'font-family'] },
  { cls: '.scoreboard-row-component',        label: 'Individual player row',                 props:['background-color', 'opacity'] },
  { cls: '.scoreboard-row-skin-background',  label: 'Skin art behind player row',            props:[{ type: 'bg-replace', hideImg: '.scoreboard-row-skin-background img' }, 'opacity', 'display', 'filter'] },
  { cls: '.scoreboard-row-skin-overlay',     label: 'Overlay on skin background',            props:['opacity', 'background-color'] },
  { cls: '.scoreboard-row-color-bar',        label: 'Team color bar on left of row',         props: ['background-color', 'display', 'opacity'] },
  { cls: '.scoreboard-row-hover-overlay',    label: 'Hover effect on player rows',           props:['display', 'opacity', 'background-color'] },
  { cls: '.scoreboard-row-player-name',      label: 'Player name in scoreboard',             props: ['color', 'font-family'] },
  { cls: '.scoreboard-row-champ-name',       label: 'Champion name in scoreboard',           props: ['color', 'font-family', 'display'] },
  { cls: '.scoreboard-row-stat-line-primary',label: 'Primary stat value (KDA etc)',          props:['color', 'font-family', 'font-size'] },
  { cls: '.scoreboard-row-stat-line-secondary', label: 'Secondary stat value',               props: ['color', 'font-family'] },
  { cls: '.scoreboard-row-items-container',  label: 'Items icons row',                       props:['display', 'opacity'] },
  { cls: '.scoreboard-row-keystone-container', label: 'Keystone rune icon',                  props: ['display', 'opacity'] },
  { cls: '.scoreboard-row-summoner-spells-container', label: 'Summoner spells icons',        props: ['display', 'opacity'] },
  { cls: '.scoreboard-row-in-game-level',    label: 'In-game level display',                 props: ['color', 'display'] },
  { cls: '.scoreboard-row-separator',        label: 'Row separator line',                    props: ['display', 'opacity', 'background-color'] },
  { cls: '.scoreboard-stat-switcher-component', label: 'Stat column switcher control',       props: ['display', 'opacity'] },
  { cls: '.scoreboard-row-mute-indicator',   label: 'Mute indicator on player row',          props: ['display', 'opacity'] },
  { cls: '.scoreboard-updated-challenge-component', label: 'Challenge update in scoreboard', props:['display', 'opacity'] },
  { cls: '.scoreboard-row-stat-graph-container', label: 'Stat graph in row',                 props: ['display', 'opacity'] },
  ],
  },

  {
  label: 'Post-Game — Buttons & Navigation',
  collapsed: true,
  elements:[
  { cls: '.postgame-footer',            label: 'Post-game footer bar',                        props:['display', 'opacity', 'background-color'] },
  { cls: '.postgame-footer-exit-button',label: 'Exit / Play Again button',                    props: ['display', 'opacity'] },
  { cls: '.postgame-match-history-button', label: 'Match history button',                     props:['display', 'opacity'] },
  { cls: '.postgame-replay-button',     label: 'Replay button',                               props: ['display', 'opacity'] },
  { cls: '.postgame-header-button-container', label: 'Header buttons container',              props: ['display', 'opacity'] },
  { cls: '.career-postgame-sub-navigation-component', label: 'Sub-navigation tabs',           props:['display', 'opacity'] },
  { cls: '.postgame-sub-navigation-container', label: 'Sub-nav container',                    props: ['display', 'opacity', 'background-color'] },
  { cls: '.clipboard-copy-game-id-container', label: 'Copy game ID button area',              props:['display', 'opacity'] },
  ],
  },

  {
  label: 'Post-Game — Honor Screen',
  collapsed: true,
  elements:[
  { cls: '.honor-v3-postgame-notification-container', label: 'Honor notification container',  props: ['display', 'opacity'] },
  { cls: '.honor-v3-postgame-notification-contents',  label: 'Honor notification content',    props: ['display', 'opacity'] },
  { cls: '.honor-v3-postgame-notification-flair',     label: 'Honor flair decoration',        props:['display', 'opacity'] },
  { cls: '.honor-v3-postgame-notification-highlight', label: 'Honor highlight effect',        props: ['display', 'opacity'] },
  { cls: '.honor-v3-postgame-notification-icon',      label: 'Honor icon',                    props: ['display', 'opacity'] },
  ],
  },

  {
  label: 'Post-Game — Progression & Party',
  collapsed: true,
  elements:[
  { cls: '.postgame-progression-lottie-outline', label: 'Progression/XP animation',          props: ['display', 'opacity', 'animation'] },
  { cls: '.postgame-party-status-v2',            label: 'Party status display',               props: ['display', 'opacity'] },
  { cls: '.postgame-party-status-v2-display',    label: 'Party status content',               props: ['display', 'opacity'] },
  { cls: '.postgame-scoreboard-progression-honor-notification-component', label: 'Progression + honor combined', props: ['display', 'opacity'] },
  ],
  },

  {
  label: 'Lobby (V2) & Header',
  collapsed: true,
  elements:[
  { cls: '.v2-lobby-root-component',          label: 'Entire V2 Lobby Container',              props: ['background-color', 'opacity'] },
  { cls: '.v2-header-component',              label: 'V2 Lobby Header Area',                   props: ['opacity', 'scale', 'background-color'] },
  { cls: '.v2-footer-component',              label: 'V2 Footer Area',                         props: ['opacity', 'scale', 'background-color'] },
  { cls: '.lobby-header-content',             label: 'Lobby header text content',              props:['color', 'scale', 'text-shadow'] },
  { cls: '.lobby-header-map-icon',            label: 'Map icon in lobby header',               props: ['display', 'opacity', 'filter', 'scale'] },
  { cls: '.lobby-header-description',         label: 'Mode description text',                  props:['color', 'display', 'opacity'] },
  { cls: '.v2-banner-component',              label: 'Player Banner (Regalia)',                props:[{ type: 'bg-replace', hideImg: '.v2-banner-component img' }, 'scale', 'opacity'] },
  { cls: '.lobby-banner-contents',            label: 'Banner inner contents',                  props: ['opacity', 'scale'] },
  { cls: '.lobby-back-button',                label: 'Back button',                            props: ['display', 'opacity', 'scale'] },
  ],
  },

  {
  label: 'Party, Chat & Progression (V2)',
  collapsed: true,
  elements:[
  { cls: '.party-members-container',           label: 'Party members row',                      props: ['display', 'opacity', 'background-color', 'scale'] },
  { cls: '.invite-button-container',           label: 'Invite player button wrapper',           props: ['display', 'opacity', 'scale'] },
  { cls: '.invite-button',                     label: 'Invite player button (+) icon',          props: ['background-color', 'border-radius', 'scale'] },
  { cls: '.center-container',                  label: 'Find Match button area',                 props:['scale', 'opacity'] },
  { cls: '.generic-button-text',               label: 'FIND MATCH text',                        props: ['color', 'font-family', 'text-shadow'] },
  { cls: '.chat-container',                    label: 'Lobby Chat Wrapper',                     props:['scale', 'opacity', 'border-radius'] },
  { cls: '.chat-box',                          label: 'Lobby Chat Box Background',              props: ['background-color', 'opacity', 'border-radius'] },
  { cls: '.chat-divider',                      label: 'Divider line in chat',                   props: ['display', 'opacity'] },
  { cls: '.v2-parties-invite-info-panel',      label: 'Right Panel Wrapper (Invites/Pass)',     props: ['display', 'opacity', 'scale'] },
  { cls: '.pass-progression-widget',           label: 'Battle Pass Progression Widget',         props:['scale', 'opacity', 'border-radius', 'background-color'] },
  { cls: '.pass-progression-widget-level-content', label: 'Pass level text',                props: ['color', 'scale', 'text-shadow'] },
  ],
  },

  {
  label: 'Mode Picker & Game Type Cards',
  collapsed: true,
  elements:[
  { cls: '.parties-game-select-wrapper',       label: 'Game mode selection wrapper',          props: ['display', 'opacity', 'background-color'] },
  { cls: '.parties-game-navs-list',            label: 'Game mode navigation tabs row',        props: ['background-color', 'opacity', 'scale'] },
  { cls: '.parties-game-navs-item',            label: 'Individual game nav tab',              props:['background-color', 'color', 'scale'] },
  { cls: '.parties-game-type-upper-half',      label: 'Top half of mode card (icon area)',    props:['background-color', 'opacity', 'border-radius'] },
  { cls: '.parties-game-type-lower-half',      label: 'Bottom half of mode card (text)',      props: ['background-color', 'opacity', 'border-radius'] },
  { cls: '.parties-game-type-card-name',       label: 'Mode card title text',                 props: ['color', 'font-family', 'scale', 'text-shadow'] },
  { cls: '.parties-game-type-card-intro',      label: 'Mode card description text',           props: ['color', 'display', 'opacity'] },
  { cls: '.parties-game-type-card-selected-glow', label: 'Glow on selected mode card',        props:['display', 'opacity'] },
  { cls: '.parties-game-type-card-category-btn', label: 'Mode category button',               props: ['background-color', 'color', 'scale'] },
  { cls: '.parties-game-type-icon',            label: 'Mode card icon',                       props:['opacity', 'filter', 'scale'] },
  { cls: '.game-type-card',                    label: 'Entire Mode Card',                     props: ['scale', 'opacity', 'border-radius'] },
  { cls: '.quick-play-text',                   label: 'Quick Play description text',          props: ['color', 'opacity'] },
  { cls: '.arrow-footer',                      label: 'Confirm Footer Box',                   props:['display', 'opacity', 'background-color'] }
  ],
  },

  {
  label: 'Loading Screen',
  collapsed: true,
  elements:[
  { cls: '.lol-loading-screen-container',                label: 'Loading screen container',                props:['background-color', 'backdrop-filter', 'opacity', 'display'] },
  { cls: '.lol-loading-screen-default-state',            label: 'Default loading state wrapper',           props: ['background-color', 'backdrop-filter', 'opacity'] },
  { cls: '.lol-loading-screen-lol-icon',                 label: 'LoL logo / loading icon',                 props:[{ type: 'bg-replace', hideImg: '.lol-loading-screen-lol-icon img' }, 'width', 'height', 'opacity', 'display'] },
  { cls: '.lol-loading-screen-spinner',                  label: 'Loading spinner animation',               props:['display', 'opacity'] },
  { cls: '.lol-loading-screen-status-container',         label: 'Status text container',                   props: ['display', 'opacity', 'width', 'filter'] },
  { cls: '.lol-loading-screen-progress-bar-container',   label: 'Progress bar',                            props:['display', 'opacity', 'width'] },
  ],
  },

  {
  label: 'In-Game & Waiting Screens',
  collapsed: true,
  elements:[
  { cls: '.rcp-fe-lol-game-in-progress',                 label: 'Game in progress background',             props: [{ type: 'bg-replace' }, 'background-color', 'opacity'] },
  { cls: '.rcp-fe-lol-pre-end-of-game',                  label: 'Pre end-of-game screen',                  props: ['background-color', 'opacity'] },
  { cls: '.rcp-fe-lol-reconnect',                        label: 'Reconnect screen',                        props:['background-color', 'opacity'] },
  { cls: '.rcp-fe-lol-waiting-for-stats',                label: 'Waiting for stats screen',                props: ['background-color', 'opacity'] },
  ],
  },

  {
  label: 'Store',
  collapsed: true,
  elements:[
  { cls: '.store-backdrop',                              label: 'Store background / backdrop',             props:['background-color', 'background-image', 'opacity', 'display', 'filter', 'backdrop-filter'] },
  { cls: '.__rcp-fe-lol-store',                          label: 'Store root container',                    props:['background-color', 'opacity', 'display'] },
  { cls: '.store-loading',                               label: 'Store loading indicator',                 props: ['display', 'opacity', 'background-color'] },
  { cls: '.shoppefront-background',                      label: 'Storefront background image',             props:['display', 'opacity'] },
  { cls: '.horizontal-options-showcase-background',      label: 'Store showcase background',               props: ['background-color', 'display', 'opacity'] },
  ],
  },

  {
  label: 'Loot',
  collapsed: true,
  elements:[
  { cls: '.loot-backdrop',                               label: 'Loot page backdrop',                      props:['background-color', 'opacity', 'display', 'filter'] },
  { cls: '.loot-backdrop.background-static',             label: 'Loot static background',                  props: ['background-color', 'opacity', 'display'] },
  { cls: '.loot-loading-screen',                         label: 'Loot loading screen',                     props: ['background-color', 'display', 'opacity'] },
  { cls: '.loot-milestones-tracker-wrapper',             label: 'Milestones tracker',                      props:['background-color', 'display', 'opacity'] },
  { cls: '.loot-to-store-button',                        label: 'Loot-to-store button',                    props: ['display', 'opacity'] },
  { cls: '.loot-item-visual',                            label: 'Loot item visual container',              props: ['opacity', 'filter'] },
  ],
  },

  {
  label: 'Collections & Champions',
  collapsed: true,
  elements:[
  { cls: '.collections-routes',                          label: 'Collections page routes container',       props: [{ type: 'bg-replace' }, 'background-color', 'opacity'] },
  { cls: '.collections-sub-nav-container',               label: 'Collections sub-navigation',              props:['filter', 'opacity', 'display'] },
  { cls: '.champion-thumbnail',                          label: 'Champion thumbnail card',                 props: ['opacity', 'filter', 'border-radius', 'height'] },
  { cls: '.champion-image-container',                    label: 'Champion image wrapper',                  props:['height', 'opacity', 'transition'] },
  { cls: '.champion-image',                              label: 'Champion image (splash art)',              props: ['border-radius', 'opacity', 'filter', 'height', 'transition'] },
  { cls: '.champion-name-container',                     label: 'Champion name label',                     props: ['display', 'opacity', 'color'] },
  { cls: '.champion-mastery-info',                       label: 'Champion mastery info badge',             props: ['display', 'opacity', 'background-color'] },
  { cls: '.champion-mastery-badge-container',            label: 'Mastery badge icon',                      props:['display', 'opacity', 'width'] },
  { cls: '.legendary-champion-mastery-collection-header',label: 'Legendary mastery header',                props: ['background-color', 'display', 'opacity'] },
  { cls: '.inventory-item-image-container',              label: 'Inventory item image wrapper',            props:['background-color', 'opacity'] },
  { cls: '.inventory-search',                            label: 'Inventory search input',                  props: ['background-color', 'color', 'border-color'] },
  { cls: '.collection-spell-container',                  label: 'Spell video container',                   props: ['opacity', 'display'] },
  { cls: '.owned-filter',                                label: 'Owned filter toggle',                     props:['border-color', 'display'] },
  ],
  },

  {
  label: 'Your Shop & Personalized Offers',
  collapsed: true,
  elements:[
  { cls: '.yourshop-root',                               label: 'Your Shop root container',                props:['background-color', 'background-image', 'opacity', 'display'] },
  { cls: '.yourshop-content-wrapper',                    label: 'Your Shop content wrapper',               props: ['opacity', 'display'] },
  { cls: '.personalized-offers-root',                    label: 'Personalized offers container',           props: ['background-color', 'opacity', 'display'] },
  ],
  },

  {
  label: 'Event Shop',
  collapsed: true,
  elements:[
  { cls: '.rcp-fe-lol-event-shop-application',           label: 'Event shop root container',               props: ['background-color', 'opacity', 'display'] },
  { cls: '.event-shop-index',                            label: 'Event shop index page',                   props: ['background-color', 'opacity'] },
  { cls: '.event-shop-index-header',                     label: 'Event shop index header',                 props: ['opacity', 'display'] },
  { cls: '.event-shop-page-header',                      label: 'Event shop page header',                  props:['background-color', 'opacity', 'display', 'border-color'] },
  { cls: '.event-shop-progression',                      label: 'Event shop progression section',          props:['background-color', 'opacity', 'display'] },
  { cls: '.event-shop-progression-info',                 label: 'Progression info panel',                  props: ['background-color', 'opacity', 'border-color'] },
  { cls: '.event-shop-progression-track',                label: 'Progression reward track',                props:['background-color', 'opacity', 'border-color'] },
  { cls: '.event-shop-reward-track-wrapper',             label: 'Reward track wrapper',                    props:['background-color', 'opacity', 'border-color'] },
  { cls: '.event-shop-token-shop-header',                label: 'Token shop header',                       props: ['background-color', 'opacity', 'border-color'] },
  { cls: '.event-shop-token-shop-card-available',        label: 'Available token shop card',               props: ['opacity', 'filter'] },
  { cls: '.event-shop-category-nav-bar',                 label: 'Category navigation bar',                 props:['background-color', 'border-color', 'opacity'] },
  { cls: '.event-shop-offer-card',                       label: 'Offer card',                              props: ['background-color', 'border-color', 'opacity'] },
  { cls: '.event-shop-xp-vertical-divider',              label: 'XP section divider',                      props:['display', 'opacity'] },
  { cls: '.event-shop-page-header-vertical-divider',     label: 'Header vertical divider',                 props: ['display', 'opacity'] },
  ],
  },

  {
  label: 'Mythic & Special Shops',
  collapsed: true,
  elements:[
  { cls: '.mythic-shop-backdrop',                        label: 'Mythic shop backdrop',                    props: ['background-color', 'display', 'opacity'] },
  { cls: '.moon-skin-backdrop',                          label: 'Moon skin shop backdrop',                 props: ['background-color', 'display', 'opacity'] },
  { cls: '.moon-skin-root-addon-component',              label: 'Moon skin addon root',                    props: ['display', 'opacity'] },
  { cls: '.selection-modal-wrapper',                     label: 'Selection modal wrapper',                 props: ['background-color', 'display', 'opacity'] },
  ],
  },

  {
  label: 'TFT',
  collapsed: true,
  elements:[
  { cls: '.rcp-fe-lol-tft-application-background',       label: 'TFT main background',                     props:['background-color', 'background-image', 'opacity', 'display'] },
  { cls: '.tft-home-footer-bg',                          label: 'TFT home footer background',              props: ['background-color', 'display', 'opacity', 'filter'] },
  { cls: '.tft-hub-footer-bg',                           label: 'TFT hub footer background',               props: ['background-color', 'display', 'opacity'] },
  { cls: '.rcp-fe-lol-tft-quick-play',                   label: 'TFT Quick Play section',                  props:['opacity', 'filter'] },
  { cls: '.rcp-fe-lol-tft-home',                         label: 'TFT home root',                           props: ['opacity', 'filter'] },
  ],
  },

  {
  label: 'Clash',
  collapsed: true,
  elements:[
  { cls: '.clash-root-background',                       label: 'Clash main background',                   props: ['background-color', 'opacity', 'display'] },
  { cls: '.clash-root-background-landing',               label: 'Clash landing background',                props:['background-color', 'opacity', 'display'] },
  { cls: '.clash-social-persistent',                     label: 'Clash social panel widget',               props: ['background-color', 'display', 'opacity'] },
  { cls: '.clash-roster-details',                        label: 'Clash roster details panel',              props:['background-color', 'display', 'opacity'] },
  { cls: '.clash-parallax-background',                   label: 'Clash parallax background effect',        props: ['opacity', 'display', 'filter'] },
  { cls: '.clash-tab-bracket-background',                label: 'Clash bracket tab background',            props: ['opacity', 'display', 'filter'] },
  { cls: '.clash-roster-team-logo-background',           label: 'Team logo background',                    props: ['opacity', 'display', 'filter'] },
  { cls: '.clash-logo-border',                           label: 'Clash logo border decoration',            props: ['background-color', 'display', 'opacity'] },
  { cls: '.clash-root-action-timeline-background-gradient', label: 'Timeline gradient overlay',            props:['display', 'opacity'] },
  { cls: '.clash-arurf-intro-modal',                     label: 'Clash ARURF intro modal',                 props: ['display', 'opacity'] },
  { cls: '.clash-aram-intro-modal',                      label: 'Clash ARAM intro modal',                  props:['display', 'opacity'] },
  ],
  },

  {
  label: 'Ranked & Leagues',
  collapsed: true,
  elements:[
  { cls: '.ranked-banner-component',                     label: 'Ranked banner display',                   props: ['opacity', 'display', 'height'] },
  { cls: '.ranked-rewards-component',                    label: 'Ranked rewards panel',                    props:['background-color', 'border-color', 'display', 'opacity'] },
  { cls: '.style-profile-emblem-wrapper',                label: 'Ranked emblem wrapper',                   props:['background-color', 'display', 'opacity'] },
  { cls: '.lol-leagues-right-container',                 label: 'Leagues right panel',                     props: ['opacity', 'display'] },
  ],
  },

  {
  label: 'Missions & Tracker',
  collapsed: true,
  elements:[
  { cls: '.mission-tracker-component',                   label: 'Missions tracker panel',                  props:['background-color', 'opacity', 'border-radius'] },
  { cls: '.mission-completed-button',                    label: 'Mission completed button',                props: ['opacity', 'display', 'border-radius'] },
  { cls: '.mission-tray-header',                         label: 'Missions tray header',                    props:['background-color', 'display', 'opacity'] },
  ],
  },

  {
  label: 'Global / Shared Elements',
  collapsed: true,
  elements:[
  { cls: '.lol-tooltip-component',      label: 'Tooltips (everywhere)',                       props:['display', 'opacity', 'background-color', 'border-color'] },
  { cls: '.alpha-version-panel',        label: 'Alpha version warning panel',                 props: ['display', 'opacity'] },
  { cls: '.basic-button',               label: 'Generic button style',                        props:['background-color', 'border-color', 'color', 'opacity'] },
  { cls: '.flat-input',                 label: 'Flat text input fields (all)',                 props: ['background-color', 'color', 'border-color'] },
  { cls: '.count-badge',                label: 'Notification count badges (all)',              props:['display', 'opacity', 'background-color', 'color'] },
  { cls: '.tft-set-announcement-root-element', label: 'TFT set announcement popup',           props: ['display', 'opacity'] },
  { cls: '.tft-loot-deprecation-pre-modal-wrapper', label: 'TFT loot deprecation modal',     props: ['display', 'opacity'] },
  { cls: '.animated-progress-bar',      label: 'Animated progress bars (global)',             props: ['animation', 'display'] },
  { cls: '.hover-card-root-container',  label: 'Hover cards (profile popups)',                props: ['display', 'opacity'] },
  { cls: '.social-count-badge',         label: 'Social notification badges',                  props: ['display', 'opacity', 'background-color'] },
  { cls: '.vng-age-rating',             label: 'Age rating display (VNG region)',             props: ['display', 'opacity'] },
  ],
  },

  {
  label: 'Activity Center (Right Panel)',
  collapsed: true,
  elements:[
  { cls: '.activity-center__background-component__image', label: 'Activity center background image', props:[{ type: 'bg-replace', hideImg: '.activity-center__background-component__image img' }, 'opacity', 'display', 'filter'] },
  { cls: '.activity-center__background-component__blend', label: 'Background blend overlay',         props: ['opacity', 'display', 'background-color'] },
  { cls: '.activity-center__header_title',     label: 'Activity center main title',                  props:['color', 'font-family', 'font-size', 'display'] },
  { cls: '.activity-center__header_subtitle',  label: 'Activity center subtitle',                    props: ['color', 'display', 'opacity'] },
  { cls: '.activity-center__header_super-title', label: 'Small label above title',                   props: ['color', 'display', 'opacity'] },
  { cls: '.activity-center__header_description', label: 'Description text',                          props: ['color', 'display', 'opacity'] },
  { cls: '.activity-center__tab_content',      label: 'Individual tab item',                         props:['background-color', 'opacity'] },
  { cls: '.activity-center__tab_content_image',label: 'Tab icon/image',                              props:[{ type: 'img-replace', label: 'Replace tab icon' }, 'opacity', 'filter'] },
  { cls: '.activity-center__tab_label_display',label: 'Tab label text',                              props: ['color', 'font-size'] },
  { cls: '.activity-center__tab_label_notification', label: 'Notification badge on tab',             props:['display', 'opacity'] },
  { cls: '.activity-center__tabs_container',   label: 'Tabs sidebar container',                      props: ['background-color', 'opacity', 'display'] },
  { cls: '.activity-center__tabs_footer',      label: 'Footer below tabs',                           props:['display', 'opacity'] },
  { cls: '.activity-center__tabs_section-divider', label: 'Divider between tab sections',            props: ['display', 'opacity'] },
  { cls: '.activity-center-cta-button',        label: 'Call-to-action button',                       props: ['display', 'opacity'] },
  { cls: '.activity-center-default-activity__deeplinks-container', label: 'Deep links in activity center', props: ['display', 'opacity'] },
  { cls: '.activity-center__media-group_content', label: 'Media content area',                       props: ['display', 'opacity'] },
  { cls: '.persistent-header-opal',            label: 'Persistent header at top of panel',           props: ['display', 'opacity', 'background-color'] },
  { cls: '.persistent-header-opal__title-container', label: 'Persistent header title',               props: ['display', 'opacity'] },
  { cls: '.persistent-header-opal__divider',   label: 'Divider in persistent header',               props:['display', 'opacity'] },
  { cls: '.ac-mute-button',                    label: 'Mute button in activity center',              props: ['display', 'opacity'] },
  ],
  },

  {
  label: 'Pass & Progression Widget',
  collapsed: true,
  elements:[
  { cls: '.pass-progression-widget-wrapper',   label: 'Battle pass widget container',           props: ['display', 'opacity'] },
  { cls: '.pass-progression-widget-rewards-content', label: 'Pass rewards display',            props: ['display', 'opacity'] },
  { cls: '.pass-progression-widget-level',     label: 'Pass level display',                     props:['display', 'opacity', 'color'] },
  { cls: '.pass-progression-widget-level-progress', label: 'Level progress bar container',     props: ['display', 'opacity'] },
  { cls: '.pass-progression-current-level-progress-fillbar', label: 'Progress bar fill color', props:['background-color', 'opacity'] },
  { cls: '.pass-progression-widget-level-reward-icon', label: 'Reward icon on progress bar',   props: ['display', 'opacity'] },
  { cls: '.pass-progression-widget-next-reward-wrapper', label: 'Next reward preview',         props: ['display', 'opacity'] },
  { cls: '.next-reward-title',                 label: 'Next reward title text',                 props: ['color', 'display'] },
  { cls: '.next-reward-label',                 label: 'Next reward label',                      props: ['color', 'display'] },
  { cls: '.next-reward-xp-label',              label: 'XP needed label',                        props:['color', 'display'] },
  { cls: '.animated-progress-bar',             label: 'Animated XP/progress bar',              props: ['display', 'opacity', 'animation'] },
  ],
  },

  {
  label: 'Challenge Banner & Achievements',
  collapsed: true,
  elements:[
  { cls: '.challenge-banner-container',        label: 'Challenge banner below name',         props:['display', 'opacity'] },
  { cls: '.challenge-banner-title-container',  label: 'Challenge banner title area',          props: ['display', 'opacity'] },
  { cls: '.challenge-banner-token-container',  label: 'Challenge token icons row',            props: ['display', 'opacity'] },
  { cls: '.achievement-token',                 label: 'Individual achievement token',          props:['display', 'opacity'] },
  { cls: '.achievement-token-container',       label: 'Achievement token wrapper',             props: ['display', 'opacity'] },
  { cls: '.player-achievements-container',     label: 'All achievements container',            props: ['display', 'opacity'] },
  ],
  },

  {
  label: 'Profile Page',
  collapsed: true,
  elements:[
  { cls: '.style-profile-overview-content',      label: 'Main Profile Container',          props:['background-color', 'opacity', 'display'] },
  { cls: '.style-profile-background-image',      label: 'Profile Background Image',        props:[{ type: 'bg-replace', hideImg: '.style-profile-background-image img' }, 'opacity', 'filter'] },
  { cls: '.style-profile-summoner-name',         label: 'Summoner Name Text',              props:['color', 'font-family', 'text-shadow', 'scale', 'transition'] },
  { cls: '.style-profile-champion-mastery-score',label: 'Mastery Score Display',           props:['color', 'scale', 'display'] },
  { cls: '.style-profile-ranked-component',      label: 'Ranked Armor / Emblem Area',      props: ['scale', 'display', 'opacity', 'filter'] },
  { cls: '.style-profile-emblem-header-title',   label: 'Ranked Queue Text (e.g. SOLO)',   props: ['color', 'font-family'] },
  { cls: '.style-profile-honor-component',       label: 'Honor Shield Display',            props:['scale', 'display', 'opacity'] },
  { cls: '.style-profile-clash-banner-component',label: 'Clash Banner Display',            props: ['scale', 'display', 'opacity'] },
  { cls: '.profile-challenge-banner-tokens',     label: 'Challenge Tokens',                props:['scale', 'display', 'opacity'] },
  { cls: '.style-summoner-xp-radial-component',  label: 'Level / XP Ring Element',         props: ['scale', 'opacity', 'filter'] }
  ],
  },
];